export const Skill = {
  AWS: 'AWS',
  AZURE: 'Azure',
  CIRCLECI: 'CircleCI',
  CUCUMBER: 'Cucumber',
  DOCKER: 'Docker',
  GCP: 'GCP',
  GIT: 'git',
  GITHUB_ACTIONS: 'Github Actions',
  GRAPHQL: 'GraphQL',
  JAVASCRIPT: 'JavaScript',
  JEST: 'Jest',
  LAMBDA: 'Lambda',
  SQS_SNS: 'SQS/SNS',
  MONGODB: 'MongoDB',
  MYSQL: 'MySQL',
  NESTJS: 'NestJS',
  NEXTJS: 'NextJS',
  NODE: 'Node',
  POSTGRESQL: 'PostgreSQL',
  REACT: 'React',
  REACT_NATIVE: 'React Native',
  REDIS: 'Redis',
  REDUX: 'Redux',
  SERVERLESS_FRAMEWORK: 'Serverless Framework',
  TERRAFORM: 'Terraform',
  TYPESCRIPT: 'Typescript',
  BACKEND: 'Backend',
  FRONTEND: 'Frontend',
  FULLSTACK: 'Fullstack',
  TECHLEAD: 'Tech lead',
} as const;

type Skill = typeof Skill[keyof typeof Skill]